version: '3.8'

name: cpevent

services:
  backend:
    image: ballatipat/cpevent-go-app:latest
    ports:
      - "4000:4000"
    environment:
      ALLOW_ORIGINS_URL: http://${HOST_API:-localhost}
      DB_URL: root:password@tcp(db:3306)/mydb?charset=utf8mb4&parseTime=true
      DB_MAX_RETRY_DURATION: 24h
      DB_RETRY_DELAY: 5s
    depends_on:
      - db
    networks:
      - api-network
    restart: always

  frontend:
    image: ballatipat/cpevent-react-app:latest
    ports:
      - 80:5173
    environment:
      VITE_REACT_APP_API_URL: http://${HOST_API:-localhost}:4000
    networks:
      - app-network
    command: npm run dev
    depends_on:
      - backend
    restart: always

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - "6033:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - api-network
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8081:80"
    networks:
      - api-network
    restart: always

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  minio_client:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (mc alias set myminio http://minio:9000 your_access_key your_secret_key); 
      do echo 'Waiting for MinIO...'; sleep 3; done;
      mc mb myminio/bucketname
      "

networks:
  app-network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.1.0.0/16
         gateway: 172.1.0.1
  api-network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

volumes:
  db_data:
  minio_data:
